// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sanad.Api.Data;

#nullable disable

namespace Sanad.Api.Migrations.Admin
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20260612153126_AddDiskUsedToUsers")]
    partial class AddDiskUsedToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Sanad.Api.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedIpAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DiskUsed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastVisitAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TierId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TierId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Sanad.Api.Models.StorageTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DiskLimitBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tiers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiskLimitBytes = 1000000000L,
                            Name = "Free",
                            Price = 0m
                        },
                        new
                        {
                            Id = 2,
                            DiskLimitBytes = 5000000000L,
                            Name = "Supporter",
                            Price = 1m
                        },
                        new
                        {
                            Id = 3,
                            DiskLimitBytes = 10000000000L,
                            Name = "Individual",
                            Price = 3m
                        },
                        new
                        {
                            Id = 4,
                            DiskLimitBytes = 200000000000L,
                            Name = "Data Hoarder",
                            Price = 7m
                        });
                });

            modelBuilder.Entity("Sanad.Api.Models.AppUser", b =>
                {
                    b.HasOne("Sanad.Api.Models.StorageTier", "Tier")
                        .WithMany()
                        .HasForeignKey("TierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tier");
                });
#pragma warning restore 612, 618
        }
    }
}
